{ config, pkgs, lib, ... }:

{
  environment.systemPackages = with pkgs; [
    curl
    fastfetch
    gcc15
    git
    gnupg
    google-chrome
    jdk
    neovim
    nodejs_22
    python3
    vim
    vscode-fhs
    wget
    htop
    ulauncher
    kitty
    obs-studio
    vlc
    gimp3-with-plugins
    tree
    speedtest-cli
    bash-completion
    wmctrl
    krita
    steam
    wl-clipboard
    gnomeExtensions.clipboard-history
    mesa
    mesa-demos
    vulkan-tools
    pciutils
    libGL
    postman
    virtualenv
    starship
    gnome-tweaks
    eyedropper
    pywal
    gnomeExtensions.blur-my-shell
    jellyfin-ffmpeg
    reversal-icon-theme
    gnomeExtensions.applications-menu
    gnomeExtensions.user-themes
    gnomeExtensions.places-status-indicator
    gnomeExtensions.desktop-icons-ng-ding
    gnomeExtensions.removable-drive-menu
    gnomeExtensions.appindicator
    gnomeExtensions.vitals
    pipenv
    code-cursor-fhs
    jetbrains.idea-community
    maven
    chromedriver
    openssl
    qemu
  ];
}
  
